# Generated by Django 4.0.5 on 2023-02-03 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='createtime',
            new_name='datetime',
        ),
    ]
