# Generated by Django 4.0.5 on 2023-02-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_createtime_user_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='datetime',
            new_name='dt',
        ),
    ]
