# Generated by Django 4.0.5 on 2023-02-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_datetime_user_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
