# Generated by Django 4.0.5 on 2023-02-04 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_customer_payment_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='pay',
        ),
    ]
