# Generated by Django 4.0.5 on 2023-02-04 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_customer_pay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='Customer_info',
        ),
    ]
