# Generated by Django 4.0.5 on 2023-02-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
