# Generated by Django 4.0.5 on 2023-02-13 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_payment_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
