# Generated by Django 4.0.5 on 2023-02-23 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
