# Generated by Django 4.0.5 on 2023-02-27 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Customer_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='website.customer'),
        ),
    ]
